import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.*;
import javax.swing.*;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.Date;
import java.util.SplittableRandom;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Amir Ghafoor
 */
public final class login extends javax.swing.JFrame {

    /**
     * Creates new form design
     */
    String email=null,otp=null,mili=null;
    public login() {
        initComponents();
        titleicone();
        Thread t = new Thread(new Runnable(){
         public void run(){
        pass1.setEchoChar((char)0);

        user.requestFocus();
        user.setCaretPosition(0);
        UIManager.put("ToolTip.background", new Color(240,240,240));
         }
         });
        t.start();
    }
    public void lgn(){
        pro.setVisible(false);
        jPanel5.setVisible(true);
    }
account_profile_employee employee=new account_profile_employee();
    database_action database=new database_action();
    fetch_data fth=new fetch_data();
    email em=new email();
    database_conection conection=new database_conection();
    int cun=0;
    int ex=0;
    Timer teem;
     void dashborad_update(){
        teem=new Timer(510, (ActionEvent arg0) -> {
             cun++;
        if(cun==14){
        if(ex!=3 && conection.conn()!=null){
        pro.setVisible(false);
        jPanel5.setVisible(true);
        user.requestFocus();
        user.setCaretPosition(0);
        teem.stop();
         }else{
            
            if(ex==3){
                JLabel messageLabel = new JLabel("<html><body><p style='width: 220px;'>"+"Due to server error program going to terminate"+"</p></body></html>");
        Timer timr = new Timer(6000, (ActionEvent event) -> {
            SwingUtilities.getWindowAncestor(messageLabel).dispose();
        });
        timr.setRepeats(false);
        timr.start();
         JOptionPane.showOptionDialog(null, messageLabel,"Server connection error", JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE, null, new Object[]{}, null);
          System.exit(0);
                return;
            }else{
            cun=0;
              ex++;
            }
        }
        }
        lod.setText(lod.getText()+"•");
        if(lod.getText().length()>7){
            lod.setText("");
        }
        });
        teem.start();
    }
//    void icon(){
//        URL path110=getClass().getResource("/email.png");
//        ImageIcon photo110=new ImageIcon(new ImageIcon(path110).getImage().getScaledInstance(lb6.getWidth(),lb6.getHeight(),Image.SCALE_SMOOTH));
//        lb6.setIcon(photo110);
//       URL path11=getClass().getResource("/pro.png");
//        ImageIcon photo11=new ImageIcon(new ImageIcon(path11).getImage().getScaledInstance(lb.getWidth(),lb.getHeight(),Image.SCALE_SMOOTH));
//        lb.setIcon(photo11);
//        lb10.setIcon(photo11);
//        URL path1=getClass().getResource("/forget.png");
//        ImageIcon photo1=new ImageIcon(new ImageIcon(path1).getImage().getScaledInstance(lb1.getWidth(),lb1.getHeight(),Image.SCALE_SMOOTH));
//        lb1.setIcon(photo1);
//        lb5.setIcon(photo1);
//        URL path10=getClass().getResource("/forget.png");
//        ImageIcon photo10=new ImageIcon(new ImageIcon(path10).getImage().getScaledInstance(lb3.getWidth(),lb3.getHeight(),Image.SCALE_SMOOTH));
//        lb3.setIcon(photo10);
//        URL path12=getClass().getResource("/see.png");
//        ImageIcon photo=new ImageIcon(new ImageIcon(path12).getImage().getScaledInstance(lb2.getWidth(),lb2.getHeight(),Image.SCALE_SMOOTH));
//        lb2.setIcon(photo);
//        lb8.setIcon(photo);
//        lb9.setIcon(photo);
//        URL path13=getClass().getResource("/then.png");
//        ImageIcon photo0=new ImageIcon(new ImageIcon(path13).getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),Image.SCALE_SMOOTH));
//        jLabel2.setIcon(photo0);
//        URL path14=getClass().getResource("/bank.png");
//        ImageIcon photo2=new ImageIcon(new ImageIcon(path14).getImage().getScaledInstance(main.getWidth(),main.getHeight(),Image.SCALE_SMOOTH));
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new RoundedPanel(30);
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        jPanel3 = new RoundedPanel(30);
        user = new javax.swing.JTextField();
        lb = new javax.swing.JLabel();
        jPanel4 = new RoundedPanel(30);
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        err = new javax.swing.JLabel();
        err1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pro = new javax.swing.JPanel();
        lod = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(100, 180, 255));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("×");
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 20));

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 40, 25));

        jPanel12.setBackground(new java.awt.Color(100, 180, 255));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel12MouseExited(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("–");
        jPanel12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 25));

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 40, 25));

        jPanel1.setBackground(new java.awt.Color(220, 240, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("BANK MANAGEMENT SYSTEM + ATM SYSTEM");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 15));
        jPanel1.add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 15, 15));

        jPanel5.setBackground(new java.awt.Color(220, 240, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 6, 16, 18));

        lb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb2MouseEntered(evt);
            }
        });
        jPanel2.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 6, 18, 18));

        pass1.setBackground(new java.awt.Color(240, 240, 240));
        pass1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        pass1.setForeground(new java.awt.Color(153, 153, 153));
        pass1.setText("Enter Password");
        pass1.setBorder(null);
        pass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass1FocusGained(evt);
            }
        });
        pass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass1MouseClicked(evt);
            }
        });
        pass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass1KeyTyped(evt);
            }
        });
        jPanel2.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 3, 160, 24));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 260, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setBackground(new java.awt.Color(240, 240, 240));
        user.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        user.setForeground(new java.awt.Color(153, 153, 153));
        user.setText("Enter Username");
        user.setBorder(null);
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
        });
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userKeyTyped(evt);
            }
        });
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 3, 195, 24));
        jPanel3.add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 6, 22, 18));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, 30));

        jPanel4.setBackground(new java.awt.Color(100, 180, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel4MouseReleased(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Login");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 260, 20));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 30));
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, -1, -1));

        err.setForeground(new java.awt.Color(255, 51, 51));
        jPanel5.add(err, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 240, 20));

        err1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5.add(err1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 20));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 310, 180));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ABC Bank Limited");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 380, 70));

        jLabel10.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Developed By: Muhammad Hasnain, Kelash, Saleem Ahmed");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 430, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 400));

        pro.setBackground(new java.awt.Color(255, 255, 255));
        pro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pro.add(lod, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 210, 50, 20));

        getContentPane().add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 60, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyTyped
        // TODO add your handling code here:
        String dt=user.getText();
        char word=evt.getKeyChar();
        if(!((word==KeyEvent.VK_BACK_SPACE)||word==KeyEvent.VK_DELETE || word==KeyEvent.VK_ENTER)){
            if(dt.equals("Enter Username")){
                user.setText(null);
                user.setForeground(Color.black);
                err.setText(null);
            }
        }
        if(((word==KeyEvent.VK_BACK_SPACE)||word==KeyEvent.VK_DELETE)){
            if(dt.length()==0){
                user.setText("Enter Username");
                user.setForeground(new Color(153,153,153));
                user.setCaretPosition(0);
            }
        }
    }//GEN-LAST:event_userKeyTyped

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            pass1.requestFocus();
            pass1.setCaretPosition(0);
        }
       else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            if(user.getText().equals("Enter Username")){
                user.setText(null);
                user.setForeground(Color.black);
                err.setText(null);
            }
        }
        else if(user.getText().equals("Enter Username")){
          user.setCaretPosition(0);
        }
    }//GEN-LAST:event_userKeyPressed

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        if(user.getText().equals("Enter Username")){
        user.setCaretPosition(0);
        }
    }//GEN-LAST:event_userMouseClicked

    private void pass1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass1KeyTyped
        // TODO add your handling code here:
        String dt=pass1.getText();
        char word=evt.getKeyChar();
        if(!((word==KeyEvent.VK_BACK_SPACE)||word==KeyEvent.VK_DELETE || word==KeyEvent.VK_ENTER)){
            if(dt.equals("Enter Password")){
                pass1.setText(null);
                pass1.setEchoChar('•');
                pass1.setForeground(Color.black);
                err1.setText(null);
            }
        }
        if(((word==KeyEvent.VK_BACK_SPACE)||word==KeyEvent.VK_DELETE)){
            if(dt.length()==0){
                pass1.setEchoChar((char)0);
                pass1.setText("Enter Password");
                pass1.setForeground(new Color(153,153,153));
                pass1.setCaretPosition(0);
                URL path30=getClass().getResource("/see.png");
                ImageIcon photo30=new ImageIcon(new ImageIcon(path30).getImage().getScaledInstance(lb2.getWidth(),lb2.getHeight(),java.awt.Image.SCALE_SMOOTH));
                lb2.setIcon(photo30);
                seee=0;
            }
        }
    }//GEN-LAST:event_pass1KeyTyped

    private void pass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass1MouseClicked
        // TODO add your handling code here:
        if(pass1.getText().equals("Enter Password")){
        pass1.setCaretPosition(0);
        }
    }//GEN-LAST:event_pass1MouseClicked

    private void lb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2MouseClicked
        // TODO add your handling code here:
        if(!(pass1.getText().equals("Enter Password"))){
            if(seee==0){
                pass1.setEchoChar((char)0);
                URL path30=getClass().getResource("/unsee.jpg");
                ImageIcon photo30=new ImageIcon(new ImageIcon(path30).getImage().getScaledInstance(lb2.getWidth(),lb2.getHeight(),java.awt.Image.SCALE_SMOOTH));
                lb2.setIcon(photo30);
                seee=1;
            }
            else if(seee==1){
                pass1.setEchoChar('•');
                URL path30=getClass().getResource("/see.png");
                ImageIcon photo30=new ImageIcon(new ImageIcon(path30).getImage().getScaledInstance(lb2.getWidth(),lb2.getHeight(),java.awt.Image.SCALE_SMOOTH));
                lb2.setIcon(photo30);
                seee=0;
            }
        }
    }//GEN-LAST:event_lb2MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here
            System.exit(0);
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        // TODO add your handling code here:
        jPanel13.setToolTipText("Close program");
        color = jPanel13.getBackground();
        c = jPanel13.getForeground();
        jLabel11.setForeground(Color.white);
        jPanel13.setBackground(Color.red);
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
        // TODO add your handling code here:
        jLabel11.setForeground(c);
        jPanel13.setBackground(color);
    }//GEN-LAST:event_jPanel13MouseExited
String user_mail=null;
    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseEntered
        // TODO add your handling code here:
        c = jPanel12.getBackground();
        jPanel12.setBackground(new Color(204,204,204));
        jPanel12.setToolTipText("Minimize Program");
    }//GEN-LAST:event_jPanel12MouseEntered

    private void jPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseExited
        // TODO add your handling code here:
        jPanel12.setBackground(c);
    }//GEN-LAST:event_jPanel12MouseExited
int xm,ym;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xm=evt.getX();
        ym=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xm, y-ym);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        jPanel4.setBackground(new java.awt.Color(70, 160, 255));
        jLabel6.setForeground(Color.white);
        jLabel6.setFont(new Font("Tahoma",1,14));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        jPanel4.setBackground(new java.awt.Color(100, 180, 255));
        jLabel6.setForeground(Color.white);
        jLabel6.setFont(new Font("Tahoma",0,12));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        jPanel4.setBackground(Color.green);
        jLabel6.setForeground(Color.white);
        jLabel6.setFont(new Font("Tahoma",1,14));
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseReleased
        // TODO add your handling code here:
        jPanel4.setBackground(new java.awt.Color(100, 180, 255));
        jLabel6.setForeground(Color.white);
        jLabel6.setFont(new Font("Tahoma",0,12));
    }//GEN-LAST:event_jPanel4MouseReleased

    private void pass1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jPanel4.setBackground(Color.green);
        jLabel6.setForeground(Color.white);
        jLabel6.setFont(new Font("Tahoma",1,14));
        sign();
        }
        else if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) {
            if(pass1.getText().equals("Enter Password")){
                pass1.setText(null);
                pass1.setEchoChar('•');
                pass1.setForeground(Color.black);
                err1.setText(null);
            }
        }
        else if(pass1.getText().equals("Enter Password")){
        pass1.setCaretPosition(0);
        }
    }//GEN-LAST:event_pass1KeyPressed

    private void pass1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass1KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jPanel4.setBackground(new Color(63,173,204));
        jLabel6.setForeground(Color.black);
        jLabel6.setFont(new Font("Tahoma",0,12));
        }
    }//GEN-LAST:event_pass1KeyReleased
//void disbl(){
//    jPanel11.setBackground(new Color(255,255,255));
//        confirm.setEditable(false);
//        confirm.setText(null);
//        jPanel9.setBackground(new Color(255,255,255));
//        confirm.setBackground(new Color(255,255,255));
//        jLabel12.setText("");
//        lb4.setIcon(null);
//        et=0;
//}
    int et=0;
boolean net(){
    try {
         URL url = new URL("http://www.google.com");
         URLConnection connection = url.openConnection();
         connection.connect();
         return true;
      } catch (MalformedURLException e) {
         return false;
      } catch (IOException e) {
         return false;
      }
}
//void mail_send(){
//    if(f66.getText().equals("Enter email")){
//            er.setText("Enter email account");
//        }
//        else if(isValidEmailAddress(f66.getText())==false){
//            er.setText("Please enter valid email address");
//        }
//        else if(net()==false){
//            JOptionPane.showMessageDialog(this,"Check internet connection","Error",JOptionPane.ERROR_MESSAGE);
//        }else{
//         if(f66.getText().equals("amirghafoorcss@gmail.com") || database.check_employee(f66.getText(),"mail")==true){
//             disbl();
//            if(f66.getText().equals("amirghafoorcss@gmail.com")){
//                user_mail="amirghafoorcss@gmail.com";
//            }else{
//               user_mail=database.getPas_con();
//            }
//             er.setText(null);
//             email=f66.getText();
//             mili=f66.getText();
//             SplittableRandom s1=new SplittableRandom();
//         StringBuilder s2=new StringBuilder();
//         for(int i=0;i<6;i++){
//          s2.append(s1.nextInt(0,10));
//          }
//           otp=s2.toString();
//          //   JOptionPane.showMessageDialog(this,"Your Request is Submit. Please wait");
//          String sms_otp="Hello dear,\nYou have submit password change request. Please enter 6 digits OTP code that is : "+otp+"";
//        Thread t = new Thread(new Runnable(){
//        public void run(){
//           em.send(mili,sms_otp,"OTP confirmation");
//         }
//        });
//        t.start();
//        JOptionPane.showMessageDialog(this,"6 digits OTP send successfully");
//        f66.setText("Enter email");
//        f66.setForeground(new Color(153,153,153));
//        jPanel14.setBackground(new Color(63,173,204));
//        jLabel13.setForeground(Color.black);
//        jLabel13.setFont(new Font("Tahoma",0,12));
//        enbl();
//         }else{
//             er.setText("Email not exits in record");
//         }
//        }
//        
//}
//void enbl(){
//    jPanel11.setBackground(new Color(63,173,204));
//        et=1;
//        confirm.setEnabled(true);
//        confirm.setEditable(true);
//        confirm.setText("Enter 6 digits OTP code");
//        confirm.setForeground(new Color(153,153,153));
//        confirm.requestFocus();
//        confirm.setCaretPosition(0);
//        jPanel9.setBackground(new Color(240,240,240));
//        confirm.setBackground(new Color(240,240,240));
//        jLabel12.setText("Confirm OTP");
//        URL path111=getClass().getResource("/ok.png");
//        ImageIcon photo111=new ImageIcon(new ImageIcon(path111).getImage().getScaledInstance(lb4.getWidth(),lb4.getHeight(),Image.SCALE_SMOOTH));
//        lb4.setIcon(photo111);
//        lb7.setIcon(photo111);
//}
void sign(){
    if(user.getText().equals("Enter Username") || pass1.getText().equals("Enter Password")){
            if(user.getText().equals("Enter Username")){
                 err.setText("Enter Username");
            }
            if(pass1.getText().equals("Enter Password")){
                err1.setText("Enter password");
            }
        }else{
           if(isValidEmailAddress(user.getText())==true){
            if(fth.getPassword_admin(pass1.getText(),user.getText())==true){
            mess();
            jPanel4.setBackground(new Color(63,173,204));
           jLabel6.setForeground(Color.black);
           jLabel6.setFont(new Font("Tahoma",0,12));
            home p=new home();
            p.setVisible(true);
            this.setVisible(false);
            this.dispose();
         }else{
            JOptionPane.showMessageDialog(this,"Username or Password is Invalid","Error",JOptionPane.ERROR_MESSAGE);
        }
        }
        else{
            if(employee.getPassword_emp(pass1.getText(),user.getText())==true){
            employee.emp_account_login_status(user.getText(),"online");
            mess();
            jPanel4.setBackground(new Color(63,173,204));
           jLabel6.setForeground(Color.black);
           jLabel6.setFont(new Font("Tahoma",0,12));
            employee_portal pp=new employee_portal();
            pp.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Username or Password is Invalid","Error",JOptionPane.ERROR_MESSAGE);
        }
        }
        }
}
void mess(){
        JLabel messageLabel = new JLabel("<html><body><p style='width: 90px;'>"+"      Login successfully"+"</p></body></html>");
           Timer timr = new Timer(1000, (ActionEvent event) -> {
            SwingUtilities.getWindowAncestor(messageLabel).dispose();
           });
           timr.setRepeats(false);
           timr.start();
           JOptionPane.showOptionDialog(null, messageLabel,"Welcome", JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE, null, new Object[]{}, null);
    }
public static boolean isValidEmailAddress(String email) {
   try {
      InternetAddress em = new InternetAddress(email);
      em.validate();
      return true;
   } catch (AddressException ex) {
      return false;
   }
}
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        sign();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        // TODO add your handling code here:
        err.setText(null);
    }//GEN-LAST:event_userFocusGained

    private void pass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusGained
        // TODO add your handling code here:
        err1.setText(null);
    }//GEN-LAST:event_pass1FocusGained
//void pass_change(String tuser){
//        String pas1=user1.getText();
//        String pas2=pass3.getText();
//        String pas3=pass2.getText();
//        if(user1.getText().equals("Enter your username") || pass3.getText().equals("Enter new Password") || pass2.getText().equals("Enter confirm Password")){
//            if(user1.getText().equals("Enter your username")){
//                rr1.setText("Enter Username");
//            }
//            if(pass3.getText().equals("Enter new Password")){
//                err2.setText("Enter new password");
//            }
//            if(pass2.getText().equals("Enter confirm Password")){
//                err3.setText("Enter Confirm password");
//            }
//        }else{
//            if(pas2.length()>=8){
//                if(pas3.length()>=8){
//                    if(pas2.equals(pas3)){
//                    if(user_mail.equals(user1.getText())){
//                       if(tuser.equals("admin")){
//                           admin_pass();
//                       }else{
//                           emp_pass();
//                       }
//                        }else{
//                            rr1.setText("Username is not match with email");
//                        }
//                    }else{
//                        err3.setText("Confirm Password not matched");
//                    }
//                }else{
//                    err3.setText("Password lenght must be 8");
//                }
//            }else{
//                err2.setText("Password lenght must be 8");
//            }
//        }
//        }
//void emp_pass(){
//         Date nowdate = new Date(); 
//        String drt="Hello dear, Your Sky Bank account password is changed at "+String.valueOf(nowdate);
//        if(employee.emp_account_password_update(String.valueOf(pass3.getPassword()),user1.getText())==true){
//        jPanel16.setBackground(new Color(63,173,204));
//        jLabel15.setForeground(Color.black);
//        jLabel15.setFont(new Font("Tahoma",0,12));
//        Thread t = new Thread(new Runnable(){
//            public void run(){
//                if(net()==true){
//                em.send(mili,drt,"Security Alert");
//                }
//                }
//        });
//        t.start();
//        JOptionPane.showMessageDialog(this,"Passowrd changed successfully","Info",JOptionPane.INFORMATION_MESSAGE);
//        user1.setText("Enter your username");
//        pass3.setText("Enter new Password");
//        pass2.setText("Enter confirm Password");
//        jPanel15.setVisible(false);
//        jPanel5.setVisible(true);
//        user.setText("Enter Username");
//        user.setForeground(new Color(153,153,153));
//        pass1.setEchoChar((char)0);
//        pass1.setText("Enter Password");
//        pass1.setForeground(new Color(153,153,153));
//        URL path30=getClass().getResource("/see.png");
//        ImageIcon photo30=new ImageIcon(new ImageIcon(path30).getImage().getScaledInstance(lb2.getWidth(),lb2.getHeight(),java.awt.Image.SCALE_SMOOTH));
//        lb2.setIcon(photo30);
//        seee=0;
//        err.setText(null);
//        err1.setText(null);
//        user.setCaretPosition(0);
//        user.requestFocus();
//        user.setCaretPosition(0);
//        }else{
//        JOptionPane.showMessageDialog(this,"Username not exits","Error",JOptionPane.ERROR_MESSAGE);
//        user1.requestFocus();
//        }
//    }
//void admin_pass(){
//        Date nowdate = new Date(); 
//        String drt="Hello dear, Your Sky Bank account password is changed at "+String.valueOf(nowdate);
//        if(database.admin_account_password_update(String.valueOf(pass3.getPassword()),user1.getText())==true){
//       // JOptionPane.showMessageDialog(this,"Please Wait few seconds","Info",JOptionPane.INFORMATION_MESSAGE);
//        jPanel16.setBackground(new Color(63,173,204));
//        jLabel15.setForeground(Color.black);
//        jLabel15.setFont(new Font("Tahoma",0,12));
//        Thread t = new Thread(new Runnable(){
//            public void run(){
//                if(net()==true){
//                em.send(mili,drt,"Security Alert");
//                }
//                }
//        });
//        t.start();
//        JOptionPane.showMessageDialog(this,"Passowrd changed successfully","Info",JOptionPane.INFORMATION_MESSAGE);
//        user1.setText("Enter your username");
//        pass3.setText("Enter new Password");
//        pass2.setText("Enter confirm Password");
//        jPanel15.setVisible(false);
//        jPanel5.setVisible(true);
//        user.setText("Enter Username");
//        user.setForeground(new Color(153,153,153));
//        pass1.setEchoChar((char)0);
//        pass1.setText("Enter Password");
//        pass1.setForeground(new Color(153,153,153));
//        URL path30=getClass().getResource("/see.png");
//        ImageIcon photo30=new ImageIcon(new ImageIcon(path30).getImage().getScaledInstance(lb2.getWidth(),lb2.getHeight(),java.awt.Image.SCALE_SMOOTH));
//        lb2.setIcon(photo30);
//        seee=0;
//        err.setText(null);
//        err1.setText(null);
//        user.setCaretPosition(0);
//        user.requestFocus();
//        user.setCaretPosition(0);
//        }else{
//        JOptionPane.showMessageDialog(this,"Username not exits","Error",JOptionPane.ERROR_MESSAGE);
//        user1.requestFocus();
//        }
//    }
    private void lb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2MouseEntered
        // TODO add your handling code here:
        if(seee==0){
        lb2.setToolTipText("Show Password");
        }else{
            lb2.setToolTipText("Hide Password");
        }
    }//GEN-LAST:event_lb2MouseEntered
int seee=0;Color c,color;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel err;
    private javax.swing.JLabel err1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lod;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPanel pro;
    public static javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

    private void titleicone() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("t.png")));
    }
}
class rond extends JProgressBar {
    protected int strokeSize = 0;
    protected Color shadowColor = Color.black;
    protected boolean shady = false;
    protected boolean highQuality =true;
    protected Dimension arcs;
    protected int shadowGap = 5;
    protected int shadowOffset = 4;
    protected int shadowAlpha = 0;
    public rond(int d) {
       super();
       arcs = new Dimension(d, d);
       setOpaque(false);
      }
    @Override
    protected void paintComponent(Graphics g) {
       super.paintComponent(g);
       int width = getWidth();
       int height = getHeight();
       int shadowGap = this.shadowGap;
       Graphics2D graphics = (Graphics2D) g;
       if (highQuality) {
           graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
           RenderingHints.VALUE_ANTIALIAS_ON);
       }
       shadowGap = 1;
       graphics.setColor(getBackground());
       graphics.fillRoundRect(0, 0, width - shadowGap,
       height - shadowGap, arcs.width, arcs.height);
       graphics.setColor(getForeground());
       graphics.setStroke(new BasicStroke(strokeSize));
       graphics.drawRoundRect(0, 0, width - shadowGap,
       height - shadowGap, arcs.width, arcs.height);
       graphics.setStroke(new BasicStroke());
   }
    }
class RoundedPanel extends JPanel {
    protected int strokeSize = 0;
    protected Color shadowColor = Color.black;
    protected boolean shady = false;
    protected boolean highQuality =true;
    protected Dimension arcs;
    protected int shadowGap = 5;
    protected int shadowOffset = 4;
    protected int shadowAlpha = 0;
    public RoundedPanel(int d) {
       super();
       arcs = new Dimension(d, d);
       setOpaque(false);
      }
    @Override
    protected void paintComponent(Graphics g) {
       super.paintComponent(g);
       int width = getWidth();
       int height = getHeight();
       int shadowGap = this.shadowGap;
       Graphics2D graphics = (Graphics2D) g;
       if (highQuality) {
           graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
           RenderingHints.VALUE_ANTIALIAS_ON);
       }
       shadowGap = 1;
       graphics.setColor(getBackground());
       graphics.fillRoundRect(0, 0, width - shadowGap,
       height - shadowGap, arcs.width, arcs.height);
       graphics.setColor(getForeground());
       graphics.setStroke(new BasicStroke(strokeSize));
       graphics.drawRoundRect(0, 0, width - shadowGap,
       height - shadowGap, arcs.width, arcs.height);
       graphics.setStroke(new BasicStroke());
   }
    }
